name: Test
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    needs: [lint]
    strategy:
      matrix:
        node: [18, 20, 12]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          node-version: ${{matrix.node}}
      - name: Install
        run: npm ci
      - name: Test
        env:
          PORT: ${{ secrets.PORT }}
        run: npm run test
